-- CreateTable
CREATE TABLE "Checklist" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER NOT NULL,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "typeIntervention" TEXT,
    "identiteConfirmee" BOOLEAN,
    "siteMarque" BOOLEAN NOT NULL DEFAULT false,
    "rougeur" BOOLEAN NOT NULL DEFAULT false,
    "douleur" BOOLEAN NOT NULL DEFAULT false,
    "lesions" BOOLEAN NOT NULL DEFAULT false,
    "coteOperer" TEXT,
    "autreCote" TEXT,
    "traitementEnCours" TEXT,
    "allergie" BOOLEAN,
    "douleurEVA" BOOLEAN,
    "risque" BOOLEAN,
    "chute" BOOLEAN NOT NULL DEFAULT false,
    "confusion" BOOLEAN NOT NULL DEFAULT false,
    "escarre" BOOLEAN NOT NULL DEFAULT false,
    "saignement" BOOLEAN NOT NULL DEFAULT false,
    "autreRisque" TEXT,
    "troubleMobilite" BOOLEAN,
    "consentement" BOOLEAN,
    "informationPatient" BOOLEAN,
    "dossierSoins" BOOLEAN,
    "jeun" BOOLEAN,
    "douche" BOOLEAN,
    "preparationPeau" BOOLEAN,
    "bilanSanguin" BOOLEAN,
    "examensComplementaires" BOOLEAN,
    "premedication" BOOLEAN NOT NULL DEFAULT false,
    "perfusion" TEXT,
    "vidangeVesicale" TEXT,
    "oxygenotherapie" TEXT,
    "transfusion" TEXT,
    "horaire" TEXT,
    "ta" TEXT,
    "fc" TEXT,
    "fr" TEXT,
    "spo2" TEXT,
    "gad" TEXT,
    "temp" TEXT,
    "bijouxOtes" BOOLEAN,
    "installationSpecifique" BOOLEAN NOT NULL DEFAULT false,
    "aiderHabillage" BOOLEAN NOT NULL DEFAULT false,
    "gererInstruments" BOOLEAN NOT NULL DEFAULT false,
    "assurerTracabilite" BOOLEAN NOT NULL DEFAULT false,
    "verifierDocumentation" BOOLEAN NOT NULL DEFAULT false,
    "typeAnesthesie" TEXT,
    "heureInduction" TEXT,
    "heureIncision" TEXT,
    "heureFermeture" TEXT,
    "heureExtubation" TEXT,
    "heureSortie" TEXT,
    "surveillance" BOOLEAN NOT NULL DEFAULT false,
    "surveillanceOperatoire" BOOLEAN NOT NULL DEFAULT false,
    "gestionDouleur" BOOLEAN NOT NULL DEFAULT false,
    "surveillanceConscience" BOOLEAN NOT NULL DEFAULT false,
    "surveillanceEtat" BOOLEAN NOT NULL DEFAULT false,
    "passationDonnees" BOOLEAN NOT NULL DEFAULT false,
    "vitales" BOOLEAN NOT NULL DEFAULT false,
    "pansementSaignement" BOOLEAN,
    "pansementEcoulement" BOOLEAN,
    "etatPeau" TEXT,
    "typeDrain" TEXT,
    "quantiteDrain" TEXT,
    "aspectSecretions" TEXT,
    "eva" BOOLEAN NOT NULL DEFAULT false,
    "perfusionPost" BOOLEAN NOT NULL DEFAULT false,
    "traitementPrescrit" BOOLEAN NOT NULL DEFAULT false,
    "mobilisation" BOOLEAN NOT NULL DEFAULT false,
    "repriseMobilite" BOOLEAN NOT NULL DEFAULT false,
    "surveillanceParametres" BOOLEAN NOT NULL DEFAULT false,
    "autonomieAideHygiene" BOOLEAN NOT NULL DEFAULT false,
    "changementPansement" BOOLEAN NOT NULL DEFAULT false,
    "changementDrains" BOOLEAN NOT NULL DEFAULT false,
    "medicPrescription" BOOLEAN NOT NULL DEFAULT false,
    "surveillanceDouleur" BOOLEAN NOT NULL DEFAULT false,
    "surveillanceHydratationNutrition" BOOLEAN NOT NULL DEFAULT false,
    "surveillancePsy" BOOLEAN NOT NULL DEFAULT false,
    "educationPatient" BOOLEAN NOT NULL DEFAULT false,
    "participationSortie" BOOLEAN NOT NULL DEFAULT false,
    "dateChangement" TEXT,
    "dateAblation" TEXT,
    "dateSortie" TEXT,
    "traitements" JSONB,

    CONSTRAINT "Checklist_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "medical_forms" (
    "id" SERIAL NOT NULL,
    "userId" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "nom" TEXT NOT NULL,
    "prenom" TEXT NOT NULL,
    "sexe" TEXT,
    "dateNaissance" TIMESTAMP(3),
    "age" INTEGER,
    "nationalite" TEXT,
    "matricule" TEXT,
    "service" TEXT,
    "lit" TEXT,
    "residence" TEXT,
    "telephone" TEXT,
    "etatCivil" TEXT,
    "couvertureSociale" TEXT[],
    "groupeSanguin" TEXT,
    "poids" DOUBLE PRECISION,
    "taille" DOUBLE PRECISION,
    "allergie" BOOLEAN NOT NULL DEFAULT false,
    "allergieDetails" TEXT,
    "dateHospitalisation" TIMESTAMP(3),
    "motifHospitalisation" TEXT,
    "diagnosticMedical" TEXT,
    "diagnosticChirurgical" TEXT,
    "membreConcerne" TEXT[],
    "typeIntervention" TEXT[],
    "autreIntervention" TEXT,
    "dateIntervention" TIMESTAMP(3),
    "typeAnesthesie" TEXT[],
    "dispositifPlace" TEXT[],
    "antecedentsMedicaux" TEXT,
    "antecedentsChirurgicaux" TEXT,
    "kinesitherapie" BOOLEAN NOT NULL DEFAULT false,

    CONSTRAINT "medical_forms_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "treatments" (
    "id" SERIAL NOT NULL,
    "medicalFormId" INTEGER NOT NULL,
    "traitement" TEXT NOT NULL,
    "dose" TEXT NOT NULL,

    CONSTRAINT "treatments_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Checklist_userId_idx" ON "Checklist"("userId");

-- CreateIndex
CREATE INDEX "Checklist_date_idx" ON "Checklist"("date");

-- CreateIndex
CREATE UNIQUE INDEX "Checklist_userId_date_key" ON "Checklist"("userId", "date");

-- AddForeignKey
ALTER TABLE "treatments" ADD CONSTRAINT "treatments_medicalFormId_fkey" FOREIGN KEY ("medicalFormId") REFERENCES "medical_forms"("id") ON DELETE CASCADE ON UPDATE CASCADE;
